### ISSUE TITLE
compatibility with Raspberry Pi

### ISSUE THREAD

**Issue by bowguy** [pgiri/dispy#115]
I have a group of Raspberry Pi's running dispy just fine using version 4.7.1 - the directions are at:
https://projects.raspberrypi.org/en/projects/build-an-octapi/4
There is a note on that page:

> Note: It is crucial that you install version 4.7.1 of dispy, as later versions rely on a library that is currently incompatible with Raspbian

 What is the library?  I would like to compile/install it and move to the latest version.
FYI dispy 4.6.5 work fine on a Raspberry Pi but it doesn't seem to find other nodes on the network, just the local one.
Thanks

**Comment by pgiri** [comment]
I do not know the dependency issue mentioned in that article. However, I have installed dispy 4.8.5 (latest release) on Raspberry Pi Model B+ from release files instead of directly from pypi repository. I am guessing that the version of pip distributed with Rpi is too old and doesn't support https used with current pypi repository. It also doesn't seem to recognize dependencies in packages. To get around it, follow these steps:

1.  Download [pycos-4.6.5](https://sourceforge.net/projects/pycos/files/latest/download) and dispy [dispy-4.8.5](https://sourceforge.net/projects/dispy/files/latest/download) release files. 
2. Install pycos with `pip install pycos-4.6.5.tar.gz --upgrade`
3. dispy depends on pycos, but as mentioned above, pip doesn't recognize it and bails out installing dispy as downloaded. So unpack the file with `tar zxf dispy-4.8.5.tar.gz` and edit `dispy-4.8.5/setup.py` file to remove the line `install_requires=['pycos >= 4.6.5'],` (this is line 45), then generate dist file and install with `cd dispy-4.8.5; python setup.py sdist; pip install dist/dispy-4.8.5.tar.gz --upgrade`

I don't know if Rpi you have has same issue with pip. Have you tried installing with `pip install dispy --upgrade`? If so, what is the error message if you had problems?

**Comment by pgiri** [comment]
Just figured an alternate and easier approach:

1. Install pip for Python 2.7 by downloading [get-pip](https://bootstrap.pypa.io/get-pip.py) and installing with `python2.7 get-pip.py`
2. Now install dispy with `python2.7 -m pip install dispy --upgrade`. This complains about building wheel package, but otherwise it installs fine and works.

**Comment by bowguy** [comment]
Thanks!
I will try them ASAP.  Quick question, dispy/dispynode will not communicate across different versions.  Will they communicate with same versions but python2.7 / python 3.5 ?

**Comment by pgiri** [comment]
No, serialization with Python 3 is different from Python 2, so nodes and client have to use either Python 2 or Python 3 but not mix. Also dispy's communication protocol changes sometimes between versions, hence requirement that the versions match.

**Comment by bowguy** [comment]
OK we have success.  First you were correct that pycos was no installed.  This worked:
sudo pip3 install dispy --upgrade
Collecting dispy
  Downloading https://www.piwheels.org/simple/dispy/dispy-4.8.5-py3-none-any.whl (190kB)
    100% |████████████████████████████████| 194kB 257kB/s
Collecting pycos>=4.6.5 (from dispy)
  Downloading https://www.piwheels.org/simple/pycos/pycos-4.6.5-py3-none-any.whl (198kB)
    100% |████████████████████████████████| 204kB 309kB/s
Installing collected packages: pycos, dispy
  Found existing installation: dispy 4.7.1
    Uninstalling dispy-4.7.1:
      Successfully uninstalled dispy-4.7.1
Successfully installed dispy-4.8.5 pycos-4.6.5

This picked up the dependencies.  The next issue was in creating a cluster.  Before I used:
.cluster = dispy.JobCluster(compute, nodes=['3.14.159.*'])
This worked in 4.7.1 as it used the local IP of 3.14.159.140 but in dispy 4..8.5 it used 127.0.0.1
The fix is to call:
cluster = dispy.JobCluster(compute, ip_addr='3.14.159.140', nodes=['3.14.159.*'])
I suspect SharefJobCluster has a similar issue.
Thanks!  
Can close

**Comment by MarcScott** [comment]
I know this is closed, but thought I'd offer a quick update from RPi perspective.

Both dispy and pycos were being distributed using piwheels.org and the packages were being built on Jesse, so were not working on Buster. They should shortly both okay to work in pip with Python 3.7.x

@bowguy I've got my OctoPi working now, and will shortly be updating the project instructions (probably a little late for you though)

**Comment by bowguy** [comment]
Great!  I was wondering why Buster broke dispy on 3.7.  I had to go back to 2.7 to get it to work. I would love to see the updated instructions and would be happy to add any suggestions.
