### ISSUE TITLE
Memory leak in job.result when result is a numpy array  

### ISSUE THREAD

**Issue by lewisrb** [pgiri/dispy#169]
Using the efficient job submission method (or any other submission method) for a job whose return value is a numpy array leads to memory usage growth. This is particularly noticeable for jobs with large numpy arrays.

Calling del on the job, or job.result within the callback method does not seem to fix this issue.

Current workaround is using the .tolist() function for the numpy array.

Thanks for all your work :)

**Comment by pgiri** [comment]
The problem is only if result is numpy array, but if the array is converted (at node) to list then there is no memory leak? If it is not much trouble, can you give a simple example that exhibits this problem? Any results being sent with `dispy_provisional_result`? If possible, can you edit `__init__.py` file to add `reply.result = None` in `job_reply_process` method right after the line `job.result = deserialize(reply.result)` (around line 1835) and test?

**Comment by pgiri** [comment]
In addition, can you try adding line `job.result = None` in callback function (assuming you don't need the result later)?

**Comment by lewisrb** [comment]
I have tried for a couple of hours to replicate this with a minimal example, but was unable to replicate the results i was getting!

If you would like i can provide the original code I was using, even though it has now changed so this is no longer a problem.

**Comment by pgiri** [comment]
If it is possible for others to run the original program that caused the leak, then please attach it.
