### ISSUE TITLE
Copy file to nodes on job execution

### ISSUE THREAD

**Issue by noapex** [pgiri/dispy#2]
Hi, first of all, thanks for this great framework.
Having that said, I'd like ask if there's a way to submit a file from the client to the nodes but at job execution level. If I'm not mistaken, dependencies are for the whole cluster, so if I have hundreds of files as dependencies they would be all be copied to every node on the cluster. I'd like to avoid a shared filesystem too.
In short, I'm looking for a way to submit a file as a dependency for a job. Is there a way?

Cheers!

**Comment by pgiri** [comment]
Hello,

Well, this is sort of available. If you pass parameter 'dispy_job_depends=["file.dat"]' to cluster.submit, then "file.dat" is sent along with the job. However, the file is assumed to be small (the data is read into memory when you submit the job and sent in one chunk to the node). Note that compute function doesn't see 'dispy_job_depends' parameter - when it executes the file would've been saved at the destination path with the same name ("file.dat" in this case).

This is, as of now, undocumented (partly because of size limitation and partly because I haven't used it so likely there are issues with this feature).

**Comment by noapex** [comment]
Hi, it worked like a charm! In my case file size was small, about 3Kb at most, so it wasn't a problem.

Thank you.

**Comment by pgiri** [comment]
Great!

After your inquiry, I revamped 'dispy_job_depends' so it can be same as 'depends' parameter - files are transmitted when submitting job (without reading them into memory), so large files can also be distributed, and other dependencies such as classes, functions can be distributed. I will release dispy-3.22 tomorrow most likely. The documentation is updated as per changes in new release.

**Comment by noapex** [comment]
Excellent work! I'll try it and get back to you if I encounter any problems.
Thanks again!
