### ISSUE TITLE
Large files (passed as dependencies)  often raise an error when are being copied to nodes

### ISSUE THREAD

**Issue by albertorepo** [pgiri/dispy#51]
Hi folks,

I'm trying to do some distributed works trasnferring large files to nodes (20Mb) .
There is no problem copying it to the scheduler, but when the nodes has to take it from the scheduler, it sometimes raises an error:
`2016-11-23 12:15:58 dispynode - Copying file "/var/folders/gw/1wsx86z902z11svnmrnb1r3h0000gn/T/dispy/scheduler/156.35.105.29/wrapper_A_k0TH/./tmpqC_Dc7.npz" failed with "Traceback (most recent call last):
  File "/usr/local/bin/dispynode.py", line 790, in xfer_file_task
    assert recvd == xf.stat_buf.st_size
AssertionError`
And the whole computation on that node is aborted.

Is there any solution?

Thank you.

**Comment by pgiri** [comment]
I guess in your case dispyscheduler.py runs under OS X? I tested it with this setup and encountered the same problem. Apparently this is due to an issue with 'sendall' under BSD variants. It is now fixed in [asyncoro's github](https://github.com/pgiri/asyncoro). Can you checkout latest asyncoro git, update `__init__.py` in asyncoro package and test dispy?

**Comment by albertorepo** [comment]
Hi @pgiri 

You were totally right. I installed the last version of asyncoro package from github and it worked like a charm.

Thank you.
