### ISSUE TITLE
add structured stats for processing

### ISSUE THREAD

**Issue by tdi** [pgiri/dispy#6]
This patch adds `cluster.gets_stats()` method that returns stats in a structure that can be easily used in a program later. This is patch agains 4.2 python3 version but it can be used with python2 too. 

PS: If you would sync the newest code to github, pull requests would be easier. 

```
 ---  __init__.py.orig    2015-05-09 10:18:43.000000000 +0000
+++ __init__.py 2015-05-09 10:18:01.332000000 +0000
@@ -1599,6 +1599,32 @@
             self.asyncoro = None
             logger.debug('shutdown complete')
 
+    def structured_stats(self, compute, wall_time=None):
+        """ Returns a hash with stats """
+        cpu_time = 0.0
+        stats = {}
+        stats['nodes'] = {}
+        for ip_addr in sorted(compute.nodes, key=lambda addr: compute.nodes[addr].done,
+                              reverse=True):
+            node = compute.nodes[ip_addr]
+            if node.done:
+                secs_per_job = node.cpu_time / node.done
+            else:
+                secs_per_job = 0
+            cpu_time += node.cpu_time
+            if node.name:
+                name = ip_addr + ' (' + node.name + ')'
+            else:
+                name = ip_addr
+            stats['nodes'][name] = { "ip_addr" : ip_addr, "cpus": node.cpus, "done": node.done, "secs_per_job": secs_per_job, "cpu_time": node.cpu_time }
+        stats['total_time'] = cpu_time
+
+        if wall_time:
+            stats['wall_time'] = wall_time 
+            stats['speedup'] = float(cpu_time) / float(wall_time)
+
+        return stats
+
     def stats(self, compute, wall_time=None):
         print()
         heading = ' %30s | %5s | %7s | %10s | %13s' % \
@@ -2023,6 +2049,16 @@
         self.close()
         return True
 
+    def get_stats(self):
+        """Get statistics for cluster(s) in a computer readable format.
+        """
+        if self.start_time is None or self.end_time is None:
+            time = None
+        else:
+            time = self.end_time - self.start_time
+
+        return self._cluster.structured_stats(self._compute, time)
+
     def stats(self):
         """Show statistics for cluster(s).
 ```

**Comment by pgiri** [comment]
Great! Thank you very much.

As you might have noticed, github is not up-to-date. I will commit latest code soon including your patch.

Giri

**Comment by pgiri** [comment]
I did a bit of tweaking with this. Let me know if you are okay with the attached patch. I wish 'stats' was named 'print_stats' so new function could've been called 'stats', which is more appropriate. Fixed couple of other issues needed for getting stats working with SharedJobCluster. Added a TODO item to keep stats in each cluster instead of each node, as a node can be used by more than one cluster (right now each cluster will report total time used on that node).
Giri

 


     On Saturday, May 9, 2015 6:26 AM, Dariusz Dwornikowski <notifications@github.com> wrote:
   

 This patch adds cluster.gets_stats() method that returns stats in a structure that can be easily used in a program later.  ---  __init__.py.orig    2015-05-09 10:18:43.000000000 +0000
+++ __init__.py 2015-05-09 10:18:01.332000000 +0000
@@ -1599,6 +1599,32 @@
             self.asyncoro = None
             logger.debug('shutdown complete')

+    def structured_stats(self, compute, wall_time=None):
+        """ Returns a hash with stats """
+        cpu_time = 0.0
+        stats = {}
+        stats['nodes'] = {}
+        for ip_addr in sorted(compute.nodes, key=lambda addr: compute.nodes[addr].done,
+                              reverse=True):
+            node = compute.nodes[ip_addr]
+            if node.done:
+                secs_per_job = node.cpu_time / node.done
+            else:
+                secs_per_job = 0
+            cpu_time += node.cpu_time
+            if node.name:
+                name = ip_addr + ' (' + node.name + ')'
+            else:
+                name = ip_addr
+            stats['nodes'][name] = { "ip_addr" : ip_addr, "cpus": node.cpus, "done": node.done, "secs_per_job": secs_per_job, "cpu_time": node.cpu_time }
+        stats['total_time'] = cpu_time
+
+        if wall_time:
+            stats['wall_time'] = wall_time 
+            stats['speedup'] = float(cpu_time) / float(wall_time)
+
+        return stats
+
     def stats(self, compute, wall_time=None):
         print()
         heading = ' %30s | %5s | %7s | %10s | %13s' % \
@@ -2023,6 +2049,16 @@
         self.close()
         return True

+    def get_stats(self):
+        """Get statistics for cluster(s) in a computer readable format.
+        """
+        if self.start_time is None or self.end_time is None:
+            time = None
+        else:
+            time = self.end_time - self.start_time
+
+        return self._cluster.structured_stats(self._compute, time)
+
     def stats(self):
         """Show statistics for cluster(s).

**Comment by pgiri** [comment]
I made a bit of mess. Apparently last night I didn't commit all the changes (because I didn't include '-a' option to commit). I just realized the mistake and ran full commit, which included the patch for stats above! I get by with barely enough git I need to manage and it shows. Sorry about this; let me know if you have comments on the patch and I will acknowledge your patch in next commit!

**Comment by pgiri** [comment]
There is an issue in 'stats_info': I create namedtuple once and copy it len(compute.nodes), which is not correct. Instead, it should create len(compute.nodes) * [collections.namedtuple('NodeStats' ...)

I am working on fixing stats collection properly so instead of using node to store them, cluster should be used. Moreover, DispyNode (which  is used to pass the information to user) also has some of this information. The idea is to move DispyNode in to _Compute (from _Node). I will commit it once it is done.

**Comment by tdi** [comment]
Great. Change this as you wish. Please do not forget to close the issue once it is in.

**Comment by pgiri** [comment]
This issue has been addressed some time ago (forgot to close then).
