### ISSUE TITLE
Node does not connect to later started scheduler

### ISSUE THREAD

**Issue by yschroeder** [pgiri/dispy#61]
If a node is started with `--scheduler_node` and the scheduler is not available at startup, the node will not connect to that scheduler if it comes online later during node lifetime.

Note: In my setup auto discovery via UDP broadcast is not possible. Node and scheduler are on different networks (but without NAT/firewall)

Reproduction:
* start node with `--scheduler_node`
* start scheduler (without `-n` for the started node)
* node does not connect to scheduler

I think the node should retry the connection to its designated scheduler at regular intervals, if one is passed via the command line option. Maybe with the same interval it sends it's broadcast message.

**Comment by pgiri** [comment]
This is due to UDP broadcast not working in your case. To implement what you need requires node to try connecting to scheduler frequently (since no way to know when scheduler may come up). This probably is best done outside with a script that checks if scheduler is available and starts dispynode. For example, with:

    while 1:
        check if scheduler is ready (e.g., connect to scheduler at scheduler port)
        if ready: break
        sleep a bit (shorter intervals poll more frequently but waste little node time etc.)

    start dispynode with --scheduler_node

I am not sure if this is generic enough case to solve in dispynode. May be in cloud platforms UDP is disabled (I am not sure) and it may make sense to integrate this in dispynode. How about you try as suggested (or some other approach) and if things work for you, post what you end up using? For now I will leave this open so others can find this info (and your solution) useful.

**Comment by yschroeder** [comment]
Your solution only works for the initial case, if the scheduler goes offline during runtime of the node it will not reconnect.

Most of my connection issues circle around the UDP broadcast. After all, I think the discussion will boil down to the overall design choice of preferring auto discovery over fixed configurations. Let me for a moment ignore that UDP broadcasts exist in dispy altogether:

A dispy setup for me looks like this (this is how I plan to use it):
There is one scheduler that is a central server, always online with fixed IP address. A lot of nodes that are not known beforehand (as they are random machines in our institute) should be used for calculations. All of these nodes may join the scheduler at any point in time and may also be removed (for example due to a user shutting the machine down). Basically, the scheduler does not know anything about the nodes, only the nodes know which machine is the scheduler and connect to it at will.

Joining and leaving a scheduler works with the current version. However, it may happen that due to network errors or system updates the scheduler machine goes offline while nodes continue to run. When the scheduler comes back online, all running nodes should automatically reconnect to their scheduler. The scheduler cannot connect to the nodes as it neither knows which nodes are available nor can it send a broadcast.

I think to use dispy for really long running clusters with lots of jobs on larger setups (like my planned beowulf cluster) this needs to be solved.

**Comment by pgiri** [comment]
It should be possible to do what you need with slight change in above script:

    while 1:
        check if scheduler is ready (e.g., connect to scheduler at scheduler port)
        if not ready:
            sleep a bit (shorter intervals poll more frequently but waste little node time etc.)
            continue
        start dispynode with --scheduler_node=... --serve=1

It is not hard to integrate this into dispynode, but this requires at least two more options (one to indicate same scheduler should be used to connect every time, and one for interval to check scheduler), and keeping things simple would be better, unless these options are useful for more users / something can't be done otherwise. Again, this is not to say this won't be implemented in dispynode itself, but for now trying to understand what works (or not) for you.

**Comment by pgiri** [comment]
Committed fix for this issue. Use `ping_interval` option to set interval to discover scheduler. Default is not to discover automatically (other than once when node starts if `scheduler_node` is given).

**Comment by yschroeder** [comment]
Nice! I will test this later.

BTW: I am currently running 11k jobs on 9 machines with a total of 88 cores and dispy works fine!

**Comment by yschroeder** [comment]
Tested and works as expected.
Thanks for the fast implementation of this feature!

**Comment by yschroeder** [comment]
I think your fix broke some things...

My callback for `cluster_status` stopped working and the computation is generally messed up. The scheduler locks up waiting for clusters to finish while the nodes do not compute anything.

The feature itself works, but as soon as jobs are started things go haywire.

**Comment by pgiri** [comment]
I don't understand the problem from the description. I have tested this and it seems to work fine. `cluster_status` feature shouldn't interfere with this feature.

**Comment by yschroeder** [comment]
I will test again and try to find a minimal example. However without changing my code it works on c5f7f5551fc510ce5860fd001c286ca323159050 but does not on a7710d89a68efe8e23ea32f3cb3b1c4fc9597c2c.

**Comment by pgiri** [comment]
Try either current github or 4.7.2 release and update if you still have issue.

**Comment by yschroeder** [comment]
Could not reproduce this issue. Works fine now.
