### ISSUE TITLE
Pickle Import Error when running within a service

### ISSUE THREAD

**Issue by joelcomp1** [pgiri/dispy#89]
Curious if you guys can provide any insight as I am at a loss as to why this doesn't work right.  I am using version dispy 4.8.3 on CentOS 7.4  with Python 2.7 and have a lot of multithreaded code that I moved over to dispy.  Everything works great I can distribute it across my different machines with no issues.   

If I take the same shell script that I am running all this with and install it into a systemd service to run autonomously basically detecting new data in the DB, then spawning jobs to process etc.  I constantly get a error:

 File "/usr/bin/dispynode.py", line 191, in _dispy_job_func
    __dispy_job_args = deserialize(__dispy_job_args)
  File "/usr/lib/python2.7/site-packages/pycos/__init__.py", line 75, in deserialize
    return pickle.loads(pkl)
ImportError: No module named <File name>

for every dispy job, again if I just run all this from the command line I have no issues, when I run the same script in a service I keep getting the above error.  I am running the service as the same user/group as I am on the cmd line.  I also checked for any SELINUX issues as that can occur in CentOS a lot.  I also verified the depends list I am passing to the cluster is the same as in the cmd line case (as I would expect).  Also went to the folder where dispy is putting the data into and checked that all the files are there as I would expect.  Also modified permissions on that as well but to no avail.

I can't for the life of me figure out why dispy/pycos would be having path/permission issues when running in a different way.  If you have any suggestions or ideas they would be much appreciated!

**Comment by pgiri** [comment]
If an object has members that are defined in other modules, then pickle will refer to them with module path. When unpickling those modules must also be available with same (relative) path.

I guess you need to include more files / modules used (directly or indirectly) in your client program in `depends` parameter to `JobCluster`. In your case, since you have already had it working when starting as command, you can include all the files (or modules) in the directory (where dispynode was started as command line) and figure out which files are necessary. You can test this with just one or two jobs first to make it easier.

**Comment by joelcomp1** [comment]
thanks that helped actually it did have to do with how I was running the dispy server in terms of the working directory.  I was incorrectly focusing on the client.  All working now much thanks!
