### ISSUE TITLE
Deallocation of the nodes

### ISSUE THREAD

**Issue by mettbest** [pgiri/dispy#91]
Once the nodes are allocated, there may be the need to deallocate some of them from the JobCluster.

How this operation can be performed?

**Comment by pgiri** [comment]
You can use `set_node_cpus` method to set cpus to 0. This will stop scheduler from scheduling any more jobs. However, existing jobs will continue to execute (until they are done) on that node.

**Comment by mettbest** [comment]
Thanks for your quick answer. I set the dispy CPU to zero to one node let's say 192.168.2.187.
Then I try to open a new dispy.JobCluster with that node 192.168.2.187 but it did not find that node.

It would be nice to deallocate completely a specific node from the dispy.JobCluster by using e.g. a `deallocate_node` method so that other dispy clients may use them.

**Comment by pgiri** [comment]
I don't understand what you mean 'open new dispy.JobCluster'. If you mean that you are running more than one cluster at a time, then setting CPUs for a node affects all JobCluster instances, as nodes and jobs are actually maintained by `_Cluster` singleton. Otherwise (maintaining cluster specific nodes etc.) complicates scheduling.

Deallocating node at runtime is rather uncommon so not much work is done (so far). Can you give more details about why this feature is required and how do you intend to use it in client? It may worth implementing it for next release, but it would help to understand it better.

**Comment by mettbest** [comment]
Hi Giridhar,

Consider the following scenario:
5 nodes are allocated to cluster1 and they have to compute 5 tasks (1 each).
2 of them are over, whereas 3 are still computing.

Now, the 2 nodes are idle but you cannot allocate them in a second cluster2. That's is the reason why an "deallocation" function would really help: while deallocating the nodes you can make them available to other cluster objects.

What do you think?

**Comment by pgiri** [comment]
Programming with such allocation / deallocation is complex in non-trivial cases. Moreover, as mentioned above, the job scheduler then has to do quite a bit of work to find a cluster and node combination (instead of just a node in current case), making it rather expensive!

Note that it is possible for clients to customize job scheduling with `cluster_status` callback so above scenario can be implemented in the client program. This may not be easy as using deallocation as suggested, but not very hard either - the client can use default scheduler by default and only when certain nodes shouldn't be used, it can submit jobs on other nodes (with `submit_node` method).

**Comment by pgiri** [comment]
Attached patch partially implements deallocation. I am not sure how useful it is to apply to the main branch, but if you use it in your work, let me know.

[deallocate.txt](https://github.com/pgiri/dispy/files/1666451/deallocate.txt)

**Comment by mettbest** [comment]
Dear Giridhar, 
thanks for the patch. I am using Python2, so it is fine.
Can you please provide also a small patch of the httpd, so that I can deallocate the nodes through the web interface? I can promise I will test this new feature deeply :+1:  :)

**Comment by mettbest** [comment]
bump :+1:

**Comment by pgiri** [comment]
Attached is patch against current master that supports closing nodes with browser - in 'monitor' page, select nodes, then choose to terminate jobs or not and 'Close'. 'deallocate_node' is also now changed to 'close_node'.

To commit this feature, though, further work is needed; e.g., it should support allocating closed node to chosen cluster. The patch is only for py2.
[close_node.txt](https://github.com/pgiri/dispy/files/1887721/close_node.txt)

**Comment by pgiri** [comment]
github master now supports above functionality. Web interface has controls for these in both 'Monitor' and 'Node' pages.
